# Semana 4 - Clase 1
## Temas Selectos Proceso Químicos: Análisis de Datos con Python

# Recordando conceptos
## Ejercicio validación de contraseña segura para calentar motores
Una contraseña se considera segura si cumple con los siguientes criterios:


- Tiene al menos 8 caracteres.
- Contiene al menos una letra mayúscula.
- Contiene al menos una letra minúscula.
- Contiene al menos un número.
- Contiene al menos un símbolo.


Escribe un código que pida al usuario ingresar una contraseña segura, si la contraseña ingresada no cumple con alguno de los criterios, el programa deberá indicarlo y solicitar nuevamente la contraseña.

In [ ]:
while True: #para repetir hasta que la contraseña sea válida.
    password = input("Ingresa una contraseña segura: ")

    tiene_mayuscula = False #contadores para verificar cada condición
    tiene_minuscula = False
    tiene_numero = False
    tiene_simbolo = False

    for caracter in password:
        if caracter.isupper(): #letra mayúscula
            tiene_mayuscula = True
        elif caracter.islower(): #letra minúscula
            tiene_minuscula = True
        elif caracter.isdigit(): #número
            tiene_numero = True
        else:
            tiene_simbolo = True

    if (len(password) >= 8 and
        tiene_mayuscula and
        tiene_minuscula and
        tiene_numero and
        tiene_simbolo):
        print("Contraseña segura")
        break # se sale del bucle solo si la condición es válida
    else:
        print("La contraseña no cumple con los criterios de seguridad.")
        print("Debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un símbolo.\n")

# De diccionario a series

Si tenemos datos contenidos en un diccionario Python, podemos crear una serie a partir de él.

In [ ]:
datos22 = {'Aguascalientes': 87, 'Baja California': 2681, 'Baja California Sur': 89,
 'Campeche': 110, 'Coahuila de Zaragoza': 169, 'Colima': 867, 'Chiapas': 499,
 'Chihuahua': 2016, 'CDMX': 742, 'Durango': 125, 'Guanajuato': 4256, 'Guerrero': 1378,
 'Hidalgo': 380, 'Jalisco': 1845, 'Mexico': 3226, 'Michoacan': 2292, 'Morelos': 1149,
 'Nayarit': 186, 'Nuevo Leon': 1391, 'Oaxaca': 740, 'Puebla': 1061, 'Queretaro': 187,
 'Quintana Roo': 635, 'San Luis Potosi': 751, 'Sinaloa': 558, 'Sonora': 1723, 'Tabasco': 334, 'Tamaulipas': 467,
 'Tlaxcala': 152, 'Veracruz': 641, 'Yucatan': 54, 'Zacatecas': 1432}

In [ ]:
datos22.keys()            # ver todas las llaves

dict_keys(['Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Coahuila de Zaragoza', 'Colima', 'Chiapas', 'Chihuahua', 'CDMX', 'Durango', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico', 'Michoacan', 'Morelos', 'Nayarit', 'Nuevo Leon', 'Oaxaca', 'Puebla', 'Queretaro', 'Quintana Roo', 'San Luis Potosi', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatan', 'Zacatecas'])

In [ ]:
datos22.values()          # ver todos los valores

dict_values([87, 2681, 89, 110, 169, 867, 499, 2016, 742, 125, 4256, 1378, 380, 1845, 3226, 2292, 1149, 186, 1391, 740, 1061, 187, 635, 751, 558, 1723, 334, 467, 152, 641, 54, 1432])

In [ ]:
datos22.items()           # pares (estado, valor)

dict_items([('Aguascalientes', 87), ('Baja California', 2681), ('Baja California Sur', 89), ('Campeche', 110), ('Coahuila de Zaragoza', 169), ('Colima', 867), ('Chiapas', 499), ('Chihuahua', 2016), ('CDMX', 742), ('Durango', 125), ('Guanajuato', 4256), ('Guerrero', 1378), ('Hidalgo', 380), ('Jalisco', 1845), ('Mexico', 3226), ('Michoacan', 2292), ('Morelos', 1149), ('Nayarit', 186), ('Nuevo Leon', 1391), ('Oaxaca', 740), ('Puebla', 1061), ('Queretaro', 187), ('Quintana Roo', 635), ('San Luis Potosi', 751), ('Sinaloa', 558), ('Sonora', 1723), ('Tabasco', 334), ('Tamaulipas', 467), ('Tlaxcala', 152), ('Veracruz', 641), ('Yucatan', 54), ('Zacatecas', 1432)])

In [ ]:
import pandas as pd

In [ ]:
obj = pd.Series(datos22)

In [ ]:
obj.head()

Aguascalientes            87
Baja California         2681
Baja California Sur       89
Campeche                 110
Coahuila de Zaragoza     169
dtype: int64

In [ ]:
obj.to_dict() #Una serie se puede convertir de nuevo en un diccionario

{'Aguascalientes': 87,
 'Baja California': 2681,
 'Baja California Sur': 89,
 'Campeche': 110,
 'Coahuila de Zaragoza': 169,
 'Colima': 867,
 'Chiapas': 499,
 'Chihuahua': 2016,
 'CDMX': 742,
 'Durango': 125,
 'Guanajuato': 4256,
 'Guerrero': 1378,
 'Hidalgo': 380,
 'Jalisco': 1845,
 'Mexico': 3226,
 'Michoacan': 2292,
 'Morelos': 1149,
 'Nayarit': 186,
 'Nuevo Leon': 1391,
 'Oaxaca': 740,
 'Puebla': 1061,
 'Queretaro': 187,
 'Quintana Roo': 635,
 'San Luis Potosi': 751,
 'Sinaloa': 558,
 'Sonora': 1723,
 'Tabasco': 334,
 'Tamaulipas': 467,
 'Tlaxcala': 152,
 'Veracruz': 641,
 'Yucatan': 54,
 'Zacatecas': 1432}

# De Diccionario a Data Frame

In [ ]:
datos_22 = {'Estado': [' Aguascalientes', ' Baja California', ' Baja California Sur', ' Campeche',
               ' Coahuila de Zaragoza', ' Colima', ' Chiapas', ' Chihuahua', ' CDMX',
               ' Durango', ' Guanajuato', ' Guerrero', ' Hidalgo', ' Jalisco', ' Mexico',
               ' Michoacan', ' Morelos', 'Nayarit', ' Nuevo Leon', ' Oaxaca', ' Puebla',
               ' Queretaro', ' Quintana Roo', ' San Luis Potosi', ' Sinaloa', ' Sonora',
               ' Tabasco', ' Tamaulipas', ' Tlaxcala', ' Veracruz', ' Yucatan', ' Zacatecas'],

    'Abreviatura': ['AG', 'BC', 'BS', 'CM', 'CO', 'CL', 'CS', 'CH', 'CX',
                    'DG', 'GT', 'GR', 'HG', 'JC', 'EM', 'MI', 'MO', 'NAY',
                    'NL', 'OA', 'PU', 'QT', 'QR', 'SL', 'SI', 'SO', 'TB',
                    'TM', 'TL', 'VE', 'YU', 'ZA'],

    'Regiones': ['Noreste', 'Noroeste', 'Noroeste', 'Sureste', 'Noreste',
                 'Occidente', 'Sureste', 'Noroeste', 'Centro-Sur', 'Noroeste',
                 'Noreste', 'Centro-Sur', 'Occidente', 'Noroeste', 'Occidente',
                 'Occidente', 'Centro-Sur', 'Noroeste', 'Noreste', 'Sureste',
                 'Centro-Sur', 'Noreste', 'Sureste', 'Noreste', 'Noroeste',
                 'Noroeste', 'Sureste', 'Noreste', 'Centro-Sur', 'Sureste',
                 'Sureste', 'Noreste'],

    'Mujeres': [13, 291, 15, 13, 26, 110, 65, 237, 107, 25, 568, 133, 57, 203,
                490, 241, 109, 16, 150, 114, 123, 26, 62, 62, 37, 142, 42, 53,
                14, 86, 7, 163],

    'Hombres': [73, 2279, 74, 95, 143, 755, 432, 1776, 635, 100, 3408, 1226,
                314, 1639, 2725, 2044, 1040, 169, 1240, 626, 923, 161, 573,
                687, 515, 1521, 292, 373, 138, 555, 47, 1261],

    'No_esp': [1, 111, 0, 2, 0, 2, 2, 3, 0, 0, 280, 19, 9, 3, 11, 7, 0, 1, 1, 0,
               15, 0, 0, 2, 6, 60, 0, 41, 0, 0, 0, 8],

    'Total': [87, 2681, 89, 110, 169, 867, 499, 2016, 742, 125, 4256, 1378, 380,
              1845, 3226, 2292, 1149, 186, 1391, 740, 1061, 187, 635, 751, 558,
              1723, 334, 467, 152, 641, 54, 1432]}

In [ ]:
df = pd.DataFrame(datos_22)

In [ ]:
df

,Estado,Abreviatura,Regiones,Mujeres,Hombres,No_esp,Total
0,Aguascalientes,AG,Noreste,13,73,1,87
1,Baja California,BC,Noroeste,291,2279,111,2681
2,Baja California Sur,BS,Noroeste,15,74,0,89
3,Campeche,CM,Sureste,13,95,2,110
4,Coahuila de Zaragoza,CO,Noreste,26,143,0,169
5,Colima,CL,Occidente,110,755,2,867
6,Chiapas,CS,Sureste,65,432,2,499
7,Chihuahua,CH,Noroeste,237,1776,3,2016
8,CDMX,CX,Centro-Sur,107,635,0,742
9,Durango,DG,Noroeste,25,100,0,125
10,Guanajuato,GT,Noreste,568,3408,280,4256
11,Guerrero,GR,Centro-Sur,133,1226,19,1378
12,Hidalgo,HG,Occidente,57,314,9,380
13,Jalisco,JC,Noroeste,203,1639,3,1845
14,Mexico,EM,Occidente,490,2725,11,3226
15,Michoacan,MI,Occidente,241,2044,7,2292
16,Morelos,MO,Centro-Sur,109,1040,0,1149
17,Nayarit,NAY,Noroeste,16,169,1,186
18,Nuevo Leon,NL,Noreste,150,1240,1,1391
19,Oaxaca,OA,Sureste,114,626,0,740
20,Puebla,PU,Centro-Sur,123,923,15,1061
21,Queretaro,QT,Noreste,26,161,0,187
22,Quintana Roo,QR,Sureste,62,573,0,635
23,San Luis Potosi,SL,Noreste,62,687,2,751
24,Sinaloa,SI,Noroeste,37,515,6,558
25,Sonora,SO,Noroeste,142,1521,60,1723
26,Tabasco,TB,Sureste,42,292,0,334
27,Tamaulipas,TM,Noreste,53,373,41,467
28,Tlaxcala,TL,Centro-Sur,14,138,0,152
29,Veracruz,VE,Sureste,86,555,0,641
30,Yucatan,YU,Sureste,7,47,0,54
31,Zacatecas,ZA,Noreste,163,1261,8,1432

In [ ]:
df.head()

,Estado,Abreviatura,Regiones,Mujeres,Hombres,No_esp,Total
0,Aguascalientes,AG,Noreste,13,73,1,87
1,Baja California,BC,Noroeste,291,2279,111,2681
2,Baja California Sur,BS,Noroeste,15,74,0,89
3,Campeche,CM,Sureste,13,95,2,110
4,Coahuila de Zaragoza,CO,Noreste,26,143,0,169

In [ ]:
df["Estado"] = df["Estado"].str.strip()
df["Regiones"] = df["Regiones"].str.strip()
df["Abreviatura"] = df["Abreviatura"].str.strip()

In [ ]:
df.head()

                 Estado Abreviatura  Regiones  Mujeres  Hombres  No_esp  Total
0        Aguascalientes          AG   Noreste       13       73       1     87
1       Baja California          BC  Noroeste      291     2279     111   2681
2   Baja California Sur          BS  Noroeste       15       74       0     89
3              Campeche          CM   Sureste       13       95       2    110
4  Coahuila de Zaragoza          CO   Noreste       26      143       0    169

Obtener el nombre de mis columnas

In [ ]:
df.columns

Index(['Estado', 'Abreviatura', 'Regiones', 'Mujeres', 'Hombres', 'No_esp',
       'Total'],
      dtype='object')

In [ ]:
list(df.columns)

['Estado', 'Abreviatura', 'Regiones', 'Mujeres', 'Hombres', 'No_esp', 'Total']

In [ ]:
del df['Abreviatura']

In [ ]:
df.head()

                 Estado  Regiones  Mujeres  Hombres  No_esp  Total
0        Aguascalientes   Noreste       13       73       1     87
1       Baja California  Noroeste      291     2279     111   2681
2   Baja California Sur  Noroeste       15       74       0     89
3              Campeche   Sureste       13       95       2    110
4  Coahuila de Zaragoza   Noreste       26      143       0    169

In [ ]:
df[['Hombres','Mujeres','Estado']]

    Hombres  Mujeres                Estado
0        73       13        Aguascalientes
1      2279      291       Baja California
2        74       15   Baja California Sur
3        95       13              Campeche
4       143       26  Coahuila de Zaragoza
5       755      110                Colima
6       432       65               Chiapas
7      1776      237             Chihuahua
8       635      107                  CDMX
9       100       25               Durango
10     3408      568            Guanajuato
11     1226      133              Guerrero
12      314       57               Hidalgo
13     1639      203               Jalisco
14     2725      490                Mexico
15     2044      241             Michoacan
16     1040      109               Morelos
17      169       16               Nayarit
18     1240      150            Nuevo Leon
19      626      114                Oaxaca
20      923      123                Puebla
21      161       26             Queretaro
22      573       62          Quintana Roo
23      687       62       San Luis Potosi
24      515       37               Sinaloa
25     1521      142                Sonora
26      292       42               Tabasco
27      373       53            Tamaulipas
28      138       14              Tlaxcala
29      555       86              Veracruz
30       47        7               Yucatan
31     1261      163             Zacatecas

Si se especifica una secuencia de columnas, las columnas del dataframe se dispondrán en ese orden:

In [ ]:
df_1= pd.DataFrame(df, columns=['Hombres','Mujeres','Estado']) #crear un Data frame nuevo solo con las columnas indicadas

In [ ]:
df_1.head()

   Hombres  Mujeres                Estado
0       73       13        Aguascalientes
1     2279      291       Baja California
2       74       15   Baja California Sur
3       95       13              Campeche
4      143       26  Coahuila de Zaragoza

# Análisis estadístico

# ¿Qué es el análisis estadístico de datos?

El **análisis estadístico de datos** es el conjunto de técnicas que usamos para **describir, resumir e interpretar** datos, con el fin de **entender qué está pasando**, **comparar grupos** y, en algunos casos, **hacer inferencias o predicciones**.

---

## 1. ¿Para qué sirve?
- **Resumir** grandes cantidades de datos en información clara.
- **Detectar patrones** (tendencias, diferencias entre grupos, relaciones).
- **Tomar decisiones** basadas en evidencia (por ejemplo, en ingeniería, economía, salud, educación).
- **Evaluar hipótesis**: comprobar si un cambio o una diferencia es “real” o puede explicarse por azar.

---

## 2. Tipos de análisis estadístico

### A) Estadística descriptiva
Responde preguntas como:
- ¿Cuál es el valor “típico”?
- ¿Qué tan dispersos están los datos?
- ¿Hay valores muy altos o muy bajos (outliers)?

Herramientas comunes:
- **Medidas de tendencia central:** media, mediana, moda
- **Medidas de dispersión:** rango, varianza, desviación estándar, IQR
- **Tablas y gráficos:** histogramas, boxplots, barras, pastel (según el caso)

### B) Estadística inferencial (saca conclusiones sobre una población)
Se usa cuando tienes una **muestra** y quieres concluir algo sobre una **población**.
Incluye:
- **Intervalos de confianza**
- **Pruebas de hipótesis** (p-values)
- **Comparaciones entre grupos** (t-test, ANOVA)
- **Relaciones entre variables** (correlación, regresión)

---

## 3. Pasos típicos de un análisis estadístico
1. **Plantear el objetivo**
   - Ejemplo: “Comparar si hay diferencia entre regiones”
2. **Revisar y limpiar datos**
   - valores nulos, errores, duplicados, formatos
3. **Explorar y describir**
   - tablas resumen y estadísticas básicas
4. **Visualizar**
   - gráficos para entender distribución y comparaciones
5. **Interpretar resultados**
   - qué significa en el contexto del problema
6. *(Opcional)* **Inferir o modelar**
   - pruebas estadísticas o modelos predictivos

---

## 4. Conceptos clave
- **Variable:** característica medida (ej. Total, Hombres, Mujeres)
- **Población vs muestra:** todos los datos posibles vs una parte
- **Distribución:** forma en la que se reparten los valores
- **Outliers:** valores atípicos que pueden afectar conclusiones

---

## 5. Ejemplos de preguntas que se responden
- ¿Cuál es el **promedio** del total por estado?
- ¿Qué estados tienen los **valores más altos**?
- ¿Hay diferencias en el total **entre regiones**?
- ¿Existe relación entre **Hombres** y **Mujeres** en los datos?

---

 **Idea central:**  
El análisis estadístico convierte datos en **información útil** para **describir** y **tomar decisiones** con fundamento.

In [ ]:
from IPython.display import IFrame

pdf_url = "https://raw.githubusercontent.com/marinlopabi/Temas_Selectos_PQ_26-I/refs/heads/main/Datos-IQ-Esta.pdf"
viewer = "https://drive.google.com/viewerng/viewer?embedded=true&url=" + pdf_url

IFrame(viewer, width=1000, height=900)